# Generated by Django 3.0.5 on 2021-03-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewbooks',
            name='category',
            field=models.CharField(default=333.3333333333333, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewbooks',
            name='condition',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewbooks',
            name='description',
            field=models.CharField(default='okay', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewbooks',
            name='language',
            field=models.CharField(default='english', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewbooks',
            name='purchasedate',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viewbooks',
            name='image',
            field=models.FileField(upload_to='booksImage'),
        ),
    ]
