# Generated by Django 3.0.5 on 2021-03-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
