# Generated by Django 3.0.5 on 2021-05-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_auto_20210331_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='address',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
    ]
